import React from "react";
import InsightCard from "../components/InsightCard";
import { BrainCircuit, Info } from "lucide-react";

export default function Insights({ insightsData = [], loading = false }) {
  if (loading) {
    return (
      <div style={{ height: "400px", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text-secondary)" }}>
        Generating AI recommendations...
      </div>
    );
  }

  return (
    <div className="animate-fade-in" style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      {/* Title */}
      <div>
        <h1 style={{ color: "var(--text-primary)" }}>AI Assistant Recommendations</h1>
        <p style={{ color: "var(--text-secondary)" }}>
          Actionable notifications generated by the AI parser based on spending control, savings ratios, and emergency fund depth.
        </p>
      </div>

      {insightsData.length === 0 ? (
        <div className="card" style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "16px", padding: "48px 24px", textAlign: "center" }}>
          <BrainCircuit size={48} style={{ opacity: 0.5, color: "var(--text-muted)" }} />
          <div>
            <h3 style={{ fontSize: "1.25rem", color: "var(--text-primary)" }}>No Insights Available</h3>
            <p style={{ fontSize: "0.9rem", color: "var(--text-muted)", marginTop: "4px" }}>
              Upload a transaction statement or configure goals to feed the analysis engine.
            </p>
          </div>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "16px", maxWidth: "800px" }}>
          <div style={{
            display: "flex",
            alignItems: "center",
            gap: "8px",
            fontSize: "0.85rem",
            color: "var(--text-muted)",
            padding: "8px 12px",
            backgroundColor: "rgba(255,255,255,0.01)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius-sm)",
            width: "fit-content",
            marginBottom: "8px"
          }}>
            <Info size={14} />
            <span>AI recommends actions based on the 50/30/20 spending rule and goal gap math.</span>
          </div>
          {insightsData.map((item, idx) => (
            <InsightCard key={idx} insight={item} />
          ))}
        </div>
      )}
    </div>
  );
}
